version: 2.1

orbs:
  node: circleci/node@5

executors:
  node-executor:
    docker:
      - image: cimg/node:20

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build package
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  publish:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Publish package
          command: npm publish --access public

workflows:
  build-and-deploy:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: main
